### ISSUE TITLE
[issue] Weird extra '|' icon

### ISSUE THREAD

**Issue by cxx1234** [dwarvesf/hidden#114]
macOS 11.2.2 on intel processor.
After update to the latest version in AppStore, a translucent '|' icon appears when "Enables always hidden section" option selected.
<img width="102" alt="截屏2021-03-02 11 43 14" src="https://user-images.githubusercontent.com/4215066/109594042-0c0fea80-7b4d-11eb-820e-375559b4f8c8.png">

When the "Enables always hidden section" option unselected, the translucent icon just not shown but not disappeared, the space between icons still remains, and can be dragged with Command key holding.
<img width="80" alt="截屏2021-03-02 11 43 56" src="https://user-images.githubusercontent.com/4215066/109593977-f3073980-7b4c-11eb-9bd3-7d3f2131fc9c.png">

Thanks.

**Comment by viettrungphan** [comment]
hanks for your question , we need add a quick guide for it in the next version of the app.
Some icons you want to make it disappear forever, how to do it?  
We add new alway hide bar, drag it in the left hand side of normal bar then move any icons you want to disappear on the left of that bar, after that, simple right click on collapse (>) icon to make it disappear.

For example:

First step
Here i want to alway hide top 3 icons (BaseCamp, Warp and Skype). I also want to hide US keyboard as normally (just like old version easy to toggle and show hide).
I put top 3 icons at the left hand side of away hidden bar.
I put US keyboard at the middle of 2 bar.

<Screen Shot 2021-02-28 at 18.53.45.png>

Step 2:
Right click on > icon
The alway hide is trigger then hide top 3 icons above
<Screen Shot 2021-02-28 at 18.53.51.png>\

Step 3:
Continue left click on >
The keyboard US is hide normally.
If you left click again it will show US keyboard like step 2
If you right click you will see top 3 alway hide icons like the first image
<Screen Shot 2021-02-28 at 18.54.39.png>

**Comment by viettrungphan** [comment]
Thanks for your question , we need add a quick guide for it in the next version of the app.
Some icons you want to make it disappear forever, how to do it?  
We add new alway hide bar (translucent color), drag it in the left hand side of normal bar then move any icons you want to disappear on the left of that bar, after that, simple right click on collapse (>) icon to make it disappear.

**Comment by cxx1234** [comment]
Thanks for replying. ^_^

**Comment by viettrungphan** [comment]
Please keep it Open so other people can see this. I will close when we have new version with quick guilds.

**Comment by prestr** [comment]
Here's my menubar on Big Sur. Even after I restart my Mac the icons to the left of the translucent bar still show up. Is there an issue or am I not understanding how it's supposed to work? 

![Screen Shot 2021-03-05 at 2 44 24 PM](https://user-images.githubusercontent.com/39970655/110165791-6ca75d80-7dc1-11eb-8b79-fe3b68cee6e5.png)

**Comment by Muzosh** [comment]
> Thanks for your question , we need add a quick guide for it in the next version of the app.
> Some icons you want to make it disappear forever, how to do it?
> We add new alway hide bar (translucent color), drag it in the left hand side of normal bar then move any icons you want to disappear on the left of that bar, after that, simple right click on collapse (>) icon to make it disappear.

Hello, I'm afraid I don't understand this feature. Isn't this how main function of the app should work? You put icons on the left of the (full, original, NOT translucent) bar and when you click on (>) icon, all those icons will disappear. 

What does it mean to "disappear forever"? Like those icons will not be shown even when you click on (<) icon? This doesn't work for me and apps to the left of translucent bar are always shown as well as apps to the left of full bar. Basically I cannot see any difference between the two bars.

Thanks.

**Comment by verotheelf** [comment]
Icons to the left of the solid bar - appear when you reveal the "Hidden Bar"
Icons to the left of the translucent bar - do not appear even when you reveal the "Hidden Bar", but continue to work in the background

The difference is that there are some applications that force a menu bar icon despite its lack of purpose. You would want these completely hidden (so the application can still continue on in the background). This is unlike those in the "Hidden Bar" which you may still want accessible, but don't necessarily need enough to warrant constant visibility/just prefer a cleaner look. If you use a lot of applications, even the "Hidden Bar" can get unwieldy and either way it's annoying to have focus taken off icons you do use with those you never will. 


Your confusion likely stems from the function created to move icons between these sections. Actually really easy, but I don't think they clearly documented it in the application itself. 

In order to see the hidden section, so it's easy to move icons in/out, RIGHT click on the collapse > icon. That allows you to see both bars (solid and translucent). When you're done adjusting the icon sections, simply right click on the collapse > icon again. 

There does seem to be a glitch that makes both bars disappear, solid and translucent and leaves a weird gap where the solid bar should be, however the icons show/stay hidden correctly

And it has to be in this order, otherwise you can't "lock in" the hidden section/it won't disappear: 
Correct: (icon)(icon) |translucent| (icon)(icon) |solid| ....(<)....
Wrong: (icon)(icon) |solid| (icon)(icon) |translucent| ....(<)....

**Comment by Muzosh** [comment]
Ahhh, thanks. Right-click was the thing that helped me to understand this. I guess I got it stuck on the "mode" where I see both bars and I am supposed to adjust them and I never right-clicked the arrow to hide the translucent line. Thank you very much.

**Comment by viettrungphan** [comment]
new tutorial finished and merge to develop, please wait for the next release.
