### ISSUE TITLE
What the difference of the "hidden" and "always hidden"

### ISSUE THREAD

**Issue by yoyosbg** [dwarvesf/hidden#262]
Q1: What the difference of the "hidden" and "always hidden"

Q2: Could make the icon in the dock "always" not shown when using hidden.

**Comment by UeharaYou** [comment]
The answers based on this version (v1.9): 
Q1: Both sections fold themselves by default, but requires different key/mouse inputs to expand/fold. View the help "?" Button for more information on how to use "always hidden" area.
Q2: "Icon always not shown on expand" is exactly what "always hidden" area intends to do. 

But due to its discontinuation for almost 2 years, this version of Hidden Bar is somehow broken, "always hidden" area does not work most of the time. You might also try my unofficial maintenance version that works more reliably and coherent in user experience. (See PR #261)

For my version (unofficial v2.0), icons in both areas are hidden by default, the difference is icons in "always hidden" sections requires "Option" key pressed while clicking the expand button to reveal, ones in "hidden" area without.

**Comment by yoyosbg** [comment]
Actualy regarding Q2: I mean the hidden.app dock icon not the applications icons in the menu bar. when I click "|". the hidden.app icon appear in the dock bar. Could it be configure to not shown?
<img width="66" alt="image" src="https://github.com/dwarvesf/hidden/assets/122861122/50633bde-afd0-4917-b96a-b5dd1faea1b6">

**Comment by UeharaYou** [comment]
This is because you have "show full bar" feature on, indicating Hidden Bar to hide menus of the menu bar. This requires the icons to show in the dock to do so. If you don't want this to happen, simply switch off "show full bar" feature.

**Comment by yoyosbg** [comment]
It works after uncheck the "Use the full MenuBar on expanding" and restart.
