### ISSUE TITLE
Hidden Bar autohides when a menu bar icon/app is in use

### ISSUE THREAD

**Issue by bzx** [dwarvesf/hidden#37]
This is not really a bug, because autohiding works as designed, but...

HiddenBar (below referred to as HB) should not autohide when an icon/app from the "hidden" section is in use. For instance, my Battery icon is hidden, but I want to examine which apps are consuming most energy – after opening the Battery menu, I can only view it for 5 seconds (HB default interval for autohiding). This is not desirable because I would like to have that menu open for as much as I want. Example below with the Battery menu:

https://youtu.be/4FpfJaqFsgo

This would apply not only to things like Battery, WiFi and other system apps, but also to many other apps that are living only in the menu bar – HB autohiding will sometimes **prevent** from using that app, as I will need more time than 5 seconds to dig into a menu. See example of interacting with a popular fl.ux app:

https://youtu.be/vSt3ptgf3JA

Please fix ;)
Thanks!

**Comment by phucledien** [comment]
ok cool! We've noted this problem, and will try to solve this. Thanks for your suggestion 👍

**Comment by bzx** [comment]
Thanks – actually, now as I think of it, HB should also not autohide when the mouse is over the expanded area.

**Comment by viettrungphan** [comment]
To archive this we need Accessibility Framework to track bar button states or mouse position, this forces us to turn off Sandboxing features, Apple will not approve app without sandbox since 2012. App recording Screens events very hard to request Apple-approved. Because of this, we can't release some cool apps like Highlight Active Window. Some app you can see in AppStore like BetterSnapTools or Windows resizing submitted from a long time ago (before 2012).

**Comment by bzx** [comment]
Ok, I see.. so there isn't such a thing as "menu bar in focus" in macOS, I guess.. that's a pity.

If you implement hotkey and add an option to increase time of auto-hiding, then this would somehow aid the issues I described. 

Thanks!
