### ISSUE TITLE
[Feature Request] Support always hiding an icon from Menu Bar

### ISSUE THREAD

**Issue by SukkaW** [dwarvesf/hidden#73]
### Describe the Feature

RT.

Due to the restriction of macOS, an App have to leave an icon in either Dock or Menu Bar to maintain running in the background.
Currently I am using some Utility Apps, such as Moom (a windows management application) and PopClip. I have them run in Menu bar icon mode so that their process won't be killed by macOS. However I don't want their icon appeared in Menu bar (except they are giving me an update).

### Current behaviour

```
[icon] [to be] [hidden] [folded] | [icon] [that]  [will] [always] [show] > [other] [icons]
```

### Expected behaviour

```
[icon] [to be] [hidden] · [icon] [to be] [hidden] [folded] | [icon] [that] [will] [always] [show] > [other] [icons]
```

**Comment by phucledien** [comment]
Hi @SukkaW ✋ 
Firstly, we are very glad that you have used our app, and also give us a suggestion for improving the Hidden Bar.
About your FR, actually, we did receive this kind of feature request before( #40  #53). But we believe that it will cause more confusion for the user because they have to remember a lot of things about the icon's order to make this feature work.
Besides that, I think it will break the minimalism (a main app's philosophy), so this feature has never become true.

By the way, I have used app Moom before and I believe that they have an option to make an app run in the background so they won't show anywhere. You can check it.

**Comment by SukkaW** [comment]
> By the way, I have used app Moom before and I believe that they have an option to make an app run in the background so they won't show anywhere. You can check it.

Moom can be run in either Dock or Menu bar (Which is required for running in background on macOS). Since I doesn't want to Moom to show up neither Menu bar or Dock, so I choose Moom to run in Menu Bar mode and hopefully there might be a way to hide the icon.

Anyway, thanks for your reply and your great works!

**Comment by phucledien** [comment]
hmm... I believe faceless mode is what you need 🤔
<img width="624" alt="Screen Shot 2020-03-08 at 7 05 39 PM" src="https://user-images.githubusercontent.com/14150687/76162383-ce61c700-616f-11ea-915e-5300ea853b52.png">

**Comment by SukkaW** [comment]
@phucledien 

But Moom is not the only Utility App I am using. 

Since I have noticed there is a branch `feature/ghost-mode`, maybe someday I could see that feature merged into `master`.

Still, thanks for your great works!

**Comment by L1cardo** [comment]
@SukkaW agreed . I want ghost mode too !

**Comment by SukkaW** [comment]
@L1cardo We should be patient. There must be someq reasons they merged the related PR without including it in a newer version.

**Comment by viettrungphan** [comment]
The new status bar icon(s) from new installed app(s) will be appeared in the left hand side and ghost mode also make it disappear by default, this is the reason why we not merge it. Anybody want this feature can checkout feature/ghost-mode and enjoy it.

**Comment by s-valent** [comment]
@viettrungphan I couldn't understand how to download and setup `feature/ghost-mode` for me so I found it better to slightly modify the app by myself. I changed something I felt must always been in the app, like the menu showing from the arrow button and the ability to hide separators. In that way the ability to hide some icons forever felt like a good idea, so I made it to be controlled from the menubar by toggling separators. Like that there is no need to open menu when you need to change something. And of course there is a way to disable all this for people how do not like that functionality.

You can try [it here](https://github.com/s-valent/hidden-bar). What do you think?

**Comment by philippemiron** [comment]
I would prefer using this app as it is distributed through the App Store but right now I'm using Dozer because of this feature. They implemented this exactly like s-valent: disable by default, and with an extra separator of a different color. The always-hidden apps are shown by Option-Click.

I agree it adds a little bit of complexity but to hide the Spotlight icon and the input sources flag forever I'm all for it.

**Comment by Hybridx24** [comment]
+1 For this feature. This is a very nicely made app, and I would use it over Bartender and Vanilla (which are both clunky and have issues) - except it's missing the permanent remove feature/ghost mode. The only other option is to use the fork (which most people wouldn't know how to install) or Dozer.

I understand why you would think it's against the simplicity philosophy, but you can have the feature as an opt-in toggle switch inside the preferences. I personally would switch over to this app immediately, since otherwise, it is extremely nice and well made.

**Comment by gqbre** [comment]
This is very useful, just turn off by default

**Comment by rochakagrawal** [comment]
Any idea when this feature will be released? I see that the change has been committed to the 'develop' branch but i can't find a way to install it as a normal DMG file.  Pls can someone provide some instructions?

thanks

**Comment by s-valent** [comment]
@rochakagrawal for now the only problem is there no instruction within the app - this is the only reason the change is not released.

Unfortunately, I didn't have enough time to implement it.

The only way right now is to install xcode, download the source files and compile the app for yourself.

**Comment by rochakagrawal** [comment]
@s-valent thanks for the quick response. I don't have Xcode, do you mind compiling and just sharing the final as an attachment to this please. I WILL BE so grateful.  I don't particularly care about instructions within the app - am sure will figure it out. I hate Dozer and want to use this.  Kindly please compile and send.  Prayers to you

**Comment by wahyufahmy** [comment]
> @s-valent thanks for the quick response. I don't have Xcode, do you mind compiling and just sharing the final as an attachment to this please. I WILL BE so grateful. I don't particularly care about instructions within the app - am sure will figure it out. I hate Dozer and want to use this. Kindly please compile and send. Prayers to you

Man, I would love to get compiled code as well. I don't have Xcode either. But I will help to make the instruction or anything else for this project.

**Comment by viettrungphan** [comment]
Accept pull request and you can use this feature in latest version, also support M1.
