### ISSUE TITLE
App hides the button for stopping recording video (w/ Shift-Command 5)

### ISSUE THREAD

**Issue by indefinitus** [dwarvesf/hidden#76]
### Describe the bug

It would hide the stop icon for stopping recording screen every time even after I manually drag the icon to the not hiding area in the menu bar. 

the icon: ( ![](https://help.apple.com/assets/5E1917EE680CE2662245B09C/5E1917F1680CE2662245B0A3/en_US/5f2042dbdd8aa2fb8df198ba589841f2.png))

### Steps to reproduce

1. Shift-Command 5.
2. Start recording screen.
3. The stop icon not showing in the menu bar. (Have to manually unhide the hidden area to stop recording screen every time.)

### Expected behavior

Not hiding the stop icon when recording screen.

### Environment
 - OS: macOS 10.15.3
 - Version 1.5 (9)

**Comment by phucledien** [comment]
hi @indefinitus ✋,
Thank you for reporting the issue.
 
I can understand how inconvenient it is. But, unfortunately, there is no way to solve it, at least for now 😞 

When you start a screen recording, the stop recording menu bar button will **always** be appended to the first position in extra menu => Hidden Bar, obviously, will hide it.

We can do nothing with this, cuz Apple doesn't give the developer a way to change the position of Menu bar item.

At the moment, I suggest you can use the shortcut `Ctrl + Cmd + Esc` to stop recording.

I will keep this issue be opened. So if anyone has any idea, don't hesitate to discuss it here.
 
Feel free to contribute 👍

**Comment by romapires** [comment]
The shortcut option is great but if you **really** want the button there you can always:

1. prepare the recording (area or full screen)
1. start recording
1. switch to Finder (so that you can see all the menu bar items)
1. show all the menu bar items
1. move the stop button to the visible side
1. switch back to whatever you want to record
1. trim the start of the video where you can see yourself following these instructions

**Comment by phucledien** [comment]
I think I will close the issue. If anyone has any idea, feel free to comment here and I will reopen this 👍
